version: '3'

services:
    backend:
        build:
            context: ./backend
        command: gunicorn wesalad.wsgi --bind 0.0.0.0:8000
        ports:
            - '8000:8000'
    frontend:
        build:
            context: ./frontend
        volumes:
            - build_folder:/frontend/build
    nginx:
        image: nginx:latest
        ports:
            - 80:8080
        volumes:
            - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - ./backend/staticfiles:/staticfiles
            - build_folder:/var/www/frontend
        depends_on:
            - backend
            - frontend
volumes:
    build_folder:
